# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"
linters:
  enable:
    - depguard
    - exhaustive
    - modernize
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
          deny:
            - pkg: "github.com/pkg/errors"
              desc: only use standard library errors and fmt.Errorf for wrapping
    govet:
      disable:
        - composites
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      custom-order: false
      sections: ["standard", "default", "localmodule"]
