language: go

sudo: false

go:
  - 1.7.*

os:
  - linux
  - osx

install:
# Install all external dependencies, ensuring they are updated.
- go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq | grep -v golang-samples)

script: go test -v ./...

notifications:
  email: false
